import type { ControlAction, MidiBinding } from "./control-bindings.ts";
export type MidiPreset = { id: string; name: string; setup: string; source: string; bindings: MidiBinding[]; customTemplate: boolean };
const bind = (type: "note" | "cc", number: number, action: ControlAction, channel = 0): MidiBinding => ({ type, number, channel, action, continuous: /^(volume|low|mid|high):/.test(action) });
const decks = ["A", "B", "C"] as const;
const grid = (base: number, stride: number) => (["play", "cue", "bass", "loop"] as const).flatMap((kind, row) => decks.map((deck, column) => bind("note", base + stride * row + column, `${kind}:${deck}`)));
const volumes = (base: number) => decks.map((deck, i) => bind("cc", base + i, `volume:${deck}`));
const eq = (kind: "low" | "mid" | "high", base: number) => decks.map((deck, i) => bind("cc", base + i, `${kind}:${deck}`));
const customPads = "Create a Loud template in the manufacturer's editor: MIDI channel 1, momentary note buttons 36–47 (rows Play A/B/C, Cue A/B/C, Bass A/B/C, Loop A/B/C). Use absolute CC knobs/faders, not relative encoders. The review table gives every assignment. This is a Loud custom template, not a claim about the factory map.";
const programmer = "Choose Programmer mode manually, MIDI channel 1, and the MIDI input port (not the DAW port). Bottom four rows, left three columns: Play, Cue, Bass kill, Loop for A/B/C. Pad messages are decimal notes 11–13, 21–23, 31–33, 41–43. Loud does not send SysEx or change the controller's mode for you.";
export const MIDI_PRESETS: readonly MidiPreset[] = [
  { id: "ni-x1-mk2", name: "Native Instruments Traktor Kontrol X1 MK2", customTemplate: true, setup: "Switch from NHL to MIDI mode and configure a Loud template in NI Controller Editor. " + customPads + " Assign three absolute knobs CC 0/1/2 to volumes; CC 16/17/18 to Low EQ.", source: "https://www.native-instruments.com/fileadmin/ni_media/downloads/manuals/traktor/traktor_kontrol_x1_mk2_manual_english.pdf", bindings: [...grid(36, 3), ...volumes(0), ...eq("low", 16)] },
  { id: "ni-f1", name: "Native Instruments Traktor Kontrol F1", customTemplate: true, setup: "Use MIDI mode (SHIFT + BROWSE), not Remix Deck/NHL mode. " + customPads + " Assign the first three faders CC 0/1/2 and first three knobs CC 16/17/18 in NI Controller Editor.", source: "https://www.native-instruments.com/fileadmin/ni_media/downloads/manuals/traktor/traktor_kontrol_f1_manual_english.pdf", bindings: [...grid(36, 3), ...volumes(0), ...eq("low", 16)] },
  { id: "launchpad-mini-mk3", name: "Novation Launchpad Mini MK3", customTemplate: false, setup: programmer, source: "https://downloads.novationmusic.com/novation/launchpad-mk3/launchpad-mini-mk3-0", bindings: grid(11, 10) },
  { id: "launchpad-x", name: "Novation Launchpad X", customTemplate: false, setup: programmer, source: "https://downloads.novationmusic.com/novation/launchpad-mk3/launchpad-x", bindings: grid(11, 10) },
  { id: "launchpad-pro-mk3", name: "Novation Launchpad Pro MK3", customTemplate: false, setup: programmer, source: "https://downloads.novationmusic.com/novation/launchpad-mk3/launchpad-pro-mk3", bindings: grid(11, 10) },
  { id: "launch-control-xl-mk2", name: "Novation Launch Control XL MK2", customTemplate: true, setup: customPads + " In Novation Components set faders 1–3 to CC 0–2, knob rows 1/2/3 to CC 16–18 / 32–34 / 48–50 for Low/Mid/High. Save to a User template and select it on the hardware.", source: "https://components.novationmusic.com/launch-control-xl-mk2/templates/new", bindings: [...grid(36, 3), ...volumes(0), ...eq("low", 16), ...eq("mid", 32), ...eq("high", 48)] },
  { id: "apc-mini-mk2", name: "Akai APC mini MK2", customTemplate: false, setup: "Use Session mode, MIDI channel 1, USB port 0. Bottom four pad rows, first three columns: Play, Cue, Bass, Loop A/B/C. Faders 1–3 set deck volumes. Drum/Note modes use different messages and are not this preset.", source: "https://cdn.inmusicbrands.com/akai/attachments/APC%20mini%20mk2%20-%20Communication%20Protocol%20-%20v1.0.pdf", bindings: [...grid(0, 8), ...volumes(48)] },
  { id: "apc-key-25-mk2", name: "Akai APC Key 25 MK2", customTemplate: false, setup: "Use the clip-launch input, MIDI channel 1. Bottom four pad rows, first three columns: Play, Cue, Bass, Loop A/B/C. This preset intentionally leaves piano keys and mode-dependent knobs unmapped.", source: "https://cdn.inmusicbrands.com/akai/attachments/APC%20Key%2025%20mk2%20-%20Communication%20Protocol%20-%20v1.0.pdf", bindings: grid(0, 8) },
  { id: "nanokontrol2", name: "Korg nanoKONTROL2", customTemplate: true, setup: "Use CC mode, MIDI channel 1. In Korg Kontrol Editor set sliders 1–3 to CC 0–2; knobs 1–3 to CC 16–18; top/middle/bottom buttons 1–3 to momentary CC 32–34 / 48–50 / 64–66 for Cue / Bass / Play. Set the Play transport button to momentary CC 41. This explicit template avoids DAW-mode differences.", source: "https://www.korg.com/tmp/support/download/index.php/product/0/159/?country=us&page=product&prodid=159&prodtype=0", bindings: [...volumes(0), ...eq("low", 16), ...decks.flatMap((d,i) => [bind("cc",32+i,`cue:${d}`),bind("cc",48+i,`bass:${d}`),bind("cc",64+i,`play:${d}`)]), bind("cc",41,"play-all")] },
  { id: "midi-fighter-twister", name: "DJ TechTools Midi Fighter Twister", customTemplate: true, setup: "In Midi Fighter Utility create a Loud bank: absolute encoder CC 0–11 on MIDI channel 1, grouped four per deck as Volume/Low/Mid/High. Set encoder switches 1–3 / 5–7 / 9–11 to momentary CC 0–2 / 4–6 / 8–10 on channel 2 for Play / Cue / Bass. Disable relative and toggle modes for these controls.", source: "https://djtechtools.com/midi-fighter-setup/", bindings: [...decks.flatMap((d,i) => (["volume","low","mid","high"] as const).map((k,j) => bind("cc",i*4+j,`${k}:${d}`))), ...decks.flatMap((d,i) => [bind("cc",i,`play:${d}`,1),bind("cc",i+4,`cue:${d}`,1),bind("cc",i+8,`bass:${d}`,1)])] },
];
export function copyMidiPreset(id: string): MidiBinding[] { return MIDI_PRESETS.find(p => p.id === id)?.bindings.map(b => ({ ...b })) ?? []; }
